PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE senDB(sen_id integer primary key not null auto_increment, sen_txt text);
INSERT INTO senDB (sen_txt) VALUES('今天天气怎么样');
INSERT INTO senDB (sen_txt) VALUES('很高兴认识你');
INSERT INTO senDB (sen_txt) VALUES('打开客厅吊灯');
INSERT INTO senDB (sen_txt) VALUES('窗前明月光 ');
INSERT INTO senDB (sen_txt) VALUES('疑是地上霜 ');
INSERT INTO senDB (sen_txt) VALUES('举头望明月');
INSERT INTO senDB (sen_txt) VALUES('低头思故乡 ');
CREATE TABLE userDB(user_id integer primary key not null auto_increment, user_name text);
INSERT INTO userDB (user_name) VALUES('王海鹏');
INSERT INTO userDB (user_name) VALUES('裴培');
INSERT INTO userDB (user_name) VALUES('朱飞');
CREATE TABLE recDB(user_id integer not null, sen_id integer not null, fin CHARACTER(1), primary key(user_id, sen_id), foreign key (user_id) references userDB(user_id) on delete cascade on update cascade, foreign key (sen_id) references senDB(sen_id) on delete cascade on update cascade);
INSERT INTO "recDB" VALUES(1,1,'NO');
INSERT INTO "recDB" VALUES(1,2,'N');
INSERT INTO "recDB" VALUES(1,3,'Y');
INSERT INTO "recDB" VALUES(2,1,'Y');
INSERT INTO "recDB" VALUES(2,2,'Y');
COMMIT;
